name: Update Formula

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v4

      - name: Check for new buzz release
        id: check
        run: |
          # Get latest release from public buzz repo
          LATEST=$(curl -s https://api.github.com/repos/narthur/buzz/releases/latest | jq -r .tag_name)
          echo "latest=$LATEST" >> $GITHUB_OUTPUT
          
          # Get current version from formula
          CURRENT=$(grep -oP 'url.*tags/\K[^/]+(?=\.tar\.gz)' Formula/buzz.rb || echo "none")
          echo "current=$CURRENT" >> $GITHUB_OUTPUT
          
          if [ "$LATEST" != "$CURRENT" ]; then
            echo "needs_update=true" >> $GITHUB_OUTPUT
          else
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Update formula
        if: steps.check.outputs.needs_update == 'true'
        run: |
          VERSION="${{ steps.check.outputs.latest }}"
          URL="https://github.com/narthur/buzz/archive/refs/tags/${VERSION}.tar.gz"
          SHA256=$(curl -sL "$URL" | shasum -a 256 | cut -d ' ' -f 1)
          
          cat > Formula/buzz.rb << EOF
          class Buzz < Formula
            desc "Terminal user interface for Beeminder"
            homepage "https://github.com/narthur/buzz"
            url "${URL}"
            sha256 "${SHA256}"
            license "MIT"

            depends_on "go" => :build

            def install
              system "go", "build", *std_go_args(ldflags: "-s -w")
            end

            test do
              assert_match "buzz", shell_output("#{bin}/buzz --help 2>&1", 1)
            end
          end
          EOF

      - name: Commit and push
        if: steps.check.outputs.needs_update == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/buzz.rb
          git commit -m "buzz ${{ steps.check.outputs.latest }}"
          git push
